/*>>>>>>>>>>>>>>>>SELECT>>>>>>>>>>>>>>>>>>>>>>>>>*/

WITH COL_INFO AS (
SELECT M.*, LOWER(SUBSTR(M.CAMEL_1, 1,1))||SUBSTR(M.CAMEL_1, 2) CAMEL_2, ' = #{'||LOWER(SUBSTR(M.CAMEL_1, 1,1))||SUBSTR(M.CAMEL_1, 2)||'}' AS SET_VALUE
  FROM (
SELECT ROWNUM AS RM, A.TABLE_NAME, A.COLUMN_NAME, REPLACE(INITCAP(A.COLUMN_NAME), '_') AS CAMEL_1,  NVL(B.COMMENTS, REPLACE(INITCAP(A.COLUMN_NAME), '_')) COMMENTS, A.DATA_TYPE, A.NULLABLE
FROM ALL_TAB_COLUMNS A
   , ALL_COL_COMMENTS B
WHERE A.TABLE_NAME = B.TABLE_NAME 
  AND A.OWNER = B.OWNER 
  AND A.COLUMN_NAME = B.COLUMN_NAME 
  AND A.TABLE_NAME = 'Z01_MYBATIS_INFO'
ORDER BY A.COLUMN_ID
     )M
)
SELECT 
'        /* SQL_ID:  */' AS FIELD
  FROM DUAL
 UNION ALL 
SELECT 
'        SELECT' AS FIELD
  FROM DUAL
 UNION ALL 
SELECT CASE WHEN A.RM = 1 THEN RPAD('                A.'|| A.COLUMN_NAME, 65, ' ') ||'                /*' ||NVL(A.COMMENTS, A.CAMEL_2)||'*/' 
            ELSE RPAD('               , A.'|| A.COLUMN_NAME, 65, ' ') ||'                /*' ||NVL(A.COMMENTS, A.CAMEL_2)||'*/'                      
            END AS FIELD
  FROM COL_INFO A
 UNION ALL 
SELECT 
DISTINCT '          FROM '||A.TABLE_NAME||'  A' AS FIELD
  FROM COL_INFO A
 UNION ALL 
SELECT 
'         WHERE 1 = 1 ' AS FIELD
  FROM DUAL
 UNION ALL 
SELECT RPAD('               AND A.'|| A.COLUMN_NAME, 45, ' ') ||' = ' ||RPAD('#{'||A.CAMEL_2||'}', 20, ' ')||'             /*' ||NVL(A.COMMENTS, A.CAMEL_2)||'*/' AS FIELD
  FROM COL_INFO A
 WHERE A.NULLABLE = 'N' 
;

/*>>>>>>>>>>>>>>>>INSERT>>>>>>>>>>>>>>>>>>>>>>>>>*/
WITH COL_INFO AS (
SELECT M.*, LOWER(SUBSTR(M.CAMEL_1, 1,1))||SUBSTR(M.CAMEL_1, 2) CAMEL_2
  FROM (
SELECT ROWNUM RM, A.TABLE_NAME, A.COLUMN_NAME, REPLACE(INITCAP(A.COLUMN_NAME), '_') AS CAMEL_1,  NVL(B.COMMENTS, REPLACE(INITCAP(A.COLUMN_NAME), '_')) COMMENTS, A.DATA_TYPE, A.NULLABLE
FROM ALL_TAB_COLUMNS A
   , ALL_COL_COMMENTS B
WHERE A.TABLE_NAME = B.TABLE_NAME 
  AND A.OWNER = B.OWNER 
  AND A.COLUMN_NAME = B.COLUMN_NAME 
  AND A.TABLE_NAME = 'Z01_MYBATIS_INFO'
ORDER BY A.COLUMN_ID
     )M
)
SELECT 
'        /* SQL_ID:  */' AS FIELD
  FROM DUAL
 UNION ALL 
SELECT 
'        INSERT ' AS FIELD
  FROM DUAL
 UNION ALL 
SELECT 
DISTINCT '          INTO '||A.TABLE_NAME AS FIELD
  FROM COL_INFO A
 UNION ALL 
SELECT 
'             ( ' AS FIELD
  FROM DUAL
 UNION ALL 
SELECT CASE WHEN ROWNUM = 1 THEN RPAD('                 '|| A.COLUMN_NAME, 80, ' ') ||'  /*' ||A.COMMENTS||'  */'  
            ELSE RPAD('               , '|| A.COLUMN_NAME, 80, ' ') ||'  /*' ||A.COMMENTS||'  */' END AS FIELD
  FROM COL_INFO A
 UNION ALL 
SELECT 
'             ) VALUES ( ' AS FIELD
  FROM DUAL
 UNION ALL 
SELECT CASE WHEN ROWNUM = 1 THEN '               ' ELSE '               ,' END||CASE WHEN A.DATA_TYPE = 'DATE' THEN 'SYSDATE' 
            WHEN (A.COLUMN_NAME IN('REG_ID','UPDATE_ID') )THEN '#{_SES.username}'
            ELSE '#{'|| CAMEL_2||'}' END FIELD
  FROM COL_INFO A
 UNION ALL 
SELECT 
'               ) ' AS FIELD
  FROM DUAL
;




/*>>>>>>>>>>>>>>>>UPDATE>>>>>>>>>>>>>>>>>>>>>>>>>*/
WITH COL_INFO AS (
SELECT M.*, LOWER(SUBSTR(M.CAMEL_1, 1,1))||SUBSTR(M.CAMEL_1, 2) CAMEL_2, ' = #{'||LOWER(SUBSTR(M.CAMEL_1, 1,1))||SUBSTR(M.CAMEL_1, 2)||'}' AS SET_VALUE
  FROM (
SELECT ROWNUM AS RM, A.TABLE_NAME, A.COLUMN_NAME, REPLACE(INITCAP(A.COLUMN_NAME), '_') AS CAMEL_1,  NVL(B.COMMENTS, REPLACE(INITCAP(A.COLUMN_NAME), '_')) COMMENTS, A.DATA_TYPE, A.NULLABLE
FROM ALL_TAB_COLUMNS A
   , ALL_COL_COMMENTS B
WHERE A.TABLE_NAME = B.TABLE_NAME 
  AND A.OWNER = B.OWNER 
  AND A.COLUMN_NAME = B.COLUMN_NAME 
  AND A.TABLE_NAME = 'Z01_MYBATIS_INFO'
ORDER BY A.COLUMN_ID
     )M
)
SELECT 
'        /* SQL_ID:  */' AS FIELD
  FROM DUAL
 UNION ALL 
SELECT 
       DISTINCT '        UPDATE '||A.TABLE_NAME||' A' AS FIELD
  FROM COL_INFO A
 UNION ALL 
SELECT 
DISTINCT '           SET' FIELD
  FROM DUAL A
 UNION ALL 
SELECT CASE WHEN ROWNUM = 1 THEN RPAD('               A.'|| A.COLUMN_NAME, 80, ' ') ||RPAD(A.SET_VALUE, 20, ' ')||'                /*' ||NVL(A.COMMENTS, A.CAMEL_2)||'*/' 
            ELSE (CASE WHEN A.DATA_TYPE = 'DATE' THEN RPAD('               , A.'|| A.COLUMN_NAME, 80, ' ') ||RPAD(' = SYSDATE', 20, ' ')||'                /*' ||NVL(A.COMMENTS, A.CAMEL_2)||'*/'
                      ELSE  RPAD('               , A.'|| A.COLUMN_NAME, 80, ' ') || CASE WHEN A.COLUMN_NAME IN('REG_ID','UPDATE_ID') THEN RPAD(' = #{_SES.username}', 20, ' ') ELSE RPAD(' = #{'||A.CAMEL_2||'}', 20, ' ')||'                /*' ||NVL(A.COMMENTS, A.CAMEL_2)||'*/' END
                      END)
            END
                 AS FIELD
  FROM COL_INFO A
 WHERE A.NULLABLE = 'Y' 
 UNION ALL 
SELECT 
'         WHERE 1 = 1 ' AS FIELD
  FROM DUAL
 UNION ALL 
SELECT RPAD('           AND A.'|| A.COLUMN_NAME, 80, ' ') ||' = ' ||RPAD('#{'||A.CAMEL_2||'}', 20, ' ')||'             /*' ||NVL(A.COMMENTS, A.CAMEL_2)||'*/' AS FIELD
  FROM COL_INFO A
 WHERE A.NULLABLE = 'N' 
;



/*>>>>>>>>>>>>>>>>DELETE>>>>>>>>>>>>>>>>>>>>>>>>>*/

WITH COL_INFO AS (
SELECT M.*, LOWER(SUBSTR(M.CAMEL_1, 1,1))||SUBSTR(M.CAMEL_1, 2) CAMEL_2
  FROM (
SELECT A.TABLE_NAME, A.COLUMN_NAME, REPLACE(INITCAP(A.COLUMN_NAME), '_') AS CAMEL_1,  NVL(B.COMMENTS, REPLACE(INITCAP(A.COLUMN_NAME), '_')) COMMENTS, A.DATA_TYPE, A.NULLABLE
FROM ALL_TAB_COLUMNS A
   , ALL_COL_COMMENTS B
WHERE A.TABLE_NAME = B.TABLE_NAME 
  AND A.OWNER = B.OWNER 
  AND A.COLUMN_NAME = B.COLUMN_NAME 
  AND A.TABLE_NAME = 'Z01_CODE_DETAIL'
ORDER BY A.COLUMN_ID
     )M
)
SELECT 
'        /* SQL_ID:  */' AS FIELD
  FROM DUAL
 UNION ALL 
SELECT 
       DISTINCT '        DELETE ' AS FIELD
  FROM COL_INFO A
 UNION ALL 
SELECT 
       DISTINCT '          FROM '||A.TABLE_NAME||' A' AS FIELD
  FROM COL_INFO A
 UNION ALL 
SELECT 
'         WHERE 1 = 1 ' AS FIELD
  FROM DUAL
 UNION ALL 
SELECT 
       RPAD('           AND A.'|| A.COLUMN_NAME, 80, ' ') ||' = ' ||RPAD('#{'||A.CAMEL_2||'}', 20, ' ')||'             /*' ||NVL(A.COMMENTS, A.CAMEL_2)||'*/' AS FIELD
  FROM COL_INFO A
 WHERE A.NULLABLE = 'N' 
;
